language: android
sudo: false
android:
  components:
    - build-tools-21.1.2
    - android-23
    - add-on
    - extras
    - extra-android-m2repository
  licenses:
    - android-sdk-license-.+

script: ./gradlew lint test
